Website_URL = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
KeywordSheetPath = C:\\Users\\baner\\Downloads\\Framework_Data_Selenium\\KeywordSheet.xlsx
ObjectRepositoryPath = C:\\Users\\baner\\Downloads\\Framework_Data_Selenium\\ObjectRepository.xlsx
HTMLReportPath = C:\\Users\\baner\\eclipse-workspace\\TestingJavaProject\\src\\TestReport\\HTML_Report\\
WordFileReportPath = C:\\Users\\baner\\eclipse-workspace\\TestingJavaProject\\src\\TestReport\\WordFormatReport\\
ScreenshotFolder = C:\\Users\\baner\\Downloads\\Framework_Data_Selenium\\ScreenshotFolder\\