pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'MyJDK'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/DebajyotiSDET/SeleniumFramework.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('Publish Report') {
            steps {
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'test-output',
                    reportFiles: 'index.html',
                    reportName: 'TestNG Report'
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'test-output/**/*.*', allowEmptyArchive: true
        }
    }
}
